# WAP that generates a random number a asks the user to guess it.
"""
-> If the player's guess is higher than the actual number, the program displays "Lower number please"
-> If the User's guess is too low, the program displays "Higher Number Please"
-> When the User guesses the correct number, the program displays the number of guesses the player used to arrive at the number
"""

import random
class Perfect_Guess:

    def game_starts(self):
        random_number = random.randint(1, 100)
        a = -1
        guesses = 0
        while a != random_number:
            guesses += 1
            self.user_input = int(
                input(
                    "\nPlease enter an integer number between 1 & 100 to guess the random number generated by the code: "
                )
            )

            if self.user_input < random_number:
                print(f"{self.user_input} is very low. Please input a higher number!\n")
            elif self.user_input > random_number:
                print(f"{self.user_input} is very high. Please input a lower number!\n")

            elif self.user_input == random_number:
                print(
                    f"Congratulations! Game Cleared!\n{self.user_input} matches the Random Number.\nYou took {guesses} guesses to complete the game!\n"
                )
                break


t_p_g = Perfect_Guess()
t_p_g.game_starts()